export const ROLES = {
  ADMIN: "ADMIN",
  CANDIDATE: "CANDIDATE",
};

export const GAME_STATUS = {
  COMPLETED: "COMPLETED",
  FINALE: "FINALE",
  HINT_UNLOCKED: "HINT_UNLOCKED",
};

export const ERRORS = {
  TEAM_NOT_FOUND: "Team not found",
  SERVER_ERROR: "Server Error",
};

export const FINALE_CHALLENGES = {
  ALPHA_ASC: "ALPHA_ASC", // A-Z
  ALPHA_DESC: "ALPHA_DESC", // Z-A
  LENGTH_ASC: "LENGTH_ASC", // Shortest First
  LENGTH_DESC: "LENGTH_DESC", // Longest First
  SECOND_LETTER: "SECOND_LETTER", // 2nd Letter A-Z
  LAST_LETTER: "LAST_LETTER", // Last Letter A-Z
};

export const FINALE_DESCRIPTIONS = {
  ALPHA_ASC: "ARRANGE KEYWORDS ALPHABETICALLY (A → Z)",
  ALPHA_DESC: "ARRANGE KEYWORDS IN REVERSE ALPHABETICAL ORDER (Z → A)",
  LENGTH_ASC: "ARRANGE BY LENGTH (SHORTEST → LONGEST)",
  LENGTH_DESC: "ARRANGE BY LENGTH (LONGEST → SHORTEST)",
  SECOND_LETTER: "ARRANGE ALPHABETICALLY BY THE SECOND LETTER",
  LAST_LETTER: "ARRANGE ALPHABETICALLY BY THE LAST LETTER",
};
